name: mhf_log_shield
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  device_apps: ^2.2.0
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  battery_plus: ^7.0.0
  workmanager: ^0.9.0+3
  http: ^1.6.0
  app_usage: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true